### PR TITLE
Fix: Convert to React / ES6 (fixes #8)

### LINKED ISSUE #1: option to hide for mobile view
To be honest I think we would want to hide for mobile in most use cases but at least a config option to do so just in case?

### LINKED ISSUE #5: Missing heading ARIA
Currently, the title is readable but there is no heading role or level associated so this is just read as standard text.

If the title is configured to use the [course title ](https://github.com/cgkineo/adapt-navigationTitle/blob/da0695990c6f3bf0f1abb0985832a025ae7092bc/example.json#L10), seeing as this is already announced on course load as site `<title>`, I think we could just set this to `aria-hidden` to save repetition?

In the instance where the title differs from the [course title](https://github.com/cgkineo/adapt-navigationTitle/blob/da0695990c6f3bf0f1abb0985832a025ae7092bc/example.json#L4), I think this would need to be marked up with the appropriate aria if the title isn't included elsewhere (not included in page or menu title etc). Making this `aria-level=1` would have a knock on effect on other titles however as page and menu would become `aria-level=2` but this can be manually configured in the [_ariaLevels config](https://github.com/adaptlearning/adapt_framework/pull/3319/files).

### LINKED ISSUE #6: Add data-order support for sorting navigation
Allowed the sorting of navigation elements according to a data-order attribute in the dom
https://github.com/adaptlearning/adapt-contrib-core/pull/61

### LINKED ISSUE #7: Add support for authoring tool 1

### LINKED ISSUE #8: Convert to React / ES6

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #1 
Fixes #5 
Fixes #6 
Fixes #7 
Fixes #8 

### Changes

- JSX template
- ES6 code
- Option to hide for mobile
- Add data-order support for sorting navigation
- Schema updates

### CODE REVIEW

File: js/NavigationTitleView.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+  }
+
+  attributes() {
+    return {
+      'data-order': (Adapt.course.get('_globals')?._extensions?._navigationTitle?._navOrder || 0)
+    };
+  }
+
+  initialize() {
+    this.listenTo(Adapt, 'device:changed', this.changed);
```
Comment (chris-steele) [inline js/NavigationTitleView.js:19]: Given that you want to amend model properties it might be good for clarity to have something like:

```js
this.listenTo(Adapt, 'device:changed', this.onDeviceChanged);
```

```js
onDeviceChanged() {
    this.setIsDeviceSmall();
}
```

which simplifies `changed` to only be concerned with rendering:

```js
changed() {
    ReactDOM.render(<templates.navigationTitle {...this.model.toJSON()} />, this.el);
}
```

In `initialize` add a listener so that you can render on model changes:

```js
this.listenTo(this.model, 'all', this.changed);
```

Finally, remove `hideForMobile` and make its changes directly in the React component:

```jsx
import React from 'react';
import { classes } from 'core/js/reactHelpers';

export default function NavigationTitle(props) {
  const {
    title,
    _isDeviceSmall,
    _hideForMobile
  } = props;

  return (

    <div
      className={classes([
        'navigation-title__inner',
        _isDeviceSmall && _hideForMobile && 'u-display-none'
      ])}
    >
      {title}
    </div>

  );
}
```

**Review by chris-steele — CHANGES_REQUESTED** [review]

**Comment by chris-steele** [comment]
Also, someone will ask for the README to be updated at some point so a quick description and/or a screengrab of what this plugin does would be great 👍

File: js/NavigationTitleView.js (hunk 1 above)
Comment (swashbuck) [reply js/NavigationTitleView.js:19]: Thanks, @chris-steele.

So, I think this is fine as-is for the following reasons.

1. I purposely moved `_hideForMobile` to `NavigationTitleView.js` because I wanted to hide the parent DOM element `.navigation-logo` rather than just the child, inner div.  Leaving this element visible can create issues with Flexbox layouts and other styles as it still takes up space.  This issue was brought up in https://github.com/cgkineo/adapt-navigationLogo/issues/6 

2. `_hideForMobile` will not change.  So, we really are just rerendering when the _device size_ changes rather than any specific model properties.

Thoughts?

Comment (chris-steele) [reply js/NavigationTitleView.js:19]: Ah I see, yes, the Backbone/React hybrid does present this rather annoying problem at times with the container element. It's a simple enough plugin so if you want to leave it as is with the model manipulation in `changed` I see no harm. 👍

**Review by chris-steele — APPROVED** [review]

**Comment by swashbuck** [comment]
> Also, someone will ask for the README to be updated at some point so a quick description and/or a screengrab of what this plugin does would be great 👍

Thanks, added a screenshot.

**Review by kirsty-hames — COMMENTED** [review]
Thanks for sweeping through the issues @swashbuck, I'll comment on them separately below. 

I can confirm #6 works in the FW but `_navOrder` is missing from the schema files so this isn't available in the AT.

#1 resolved thanks.

@swashbuck, have you tested #7 in an AT1 environment? I was able to import the plugin fine without any errors but when I added the extension to a course the settings didn't display for me in the sidebar as expected (tested in AT v1.0.0-rc.2).

When using the course display title, `{{{Adapt.[course].displayTitle}}}` gets rendered as a string rather than pulling through the course display title.

**Comment by swashbuck** [comment]
> When using the course display title, {{{Adapt.[course].displayTitle}}} gets rendered as a string rather than pulling through the course display title.

@kirsty-hames What if we just made a new Boolean checkbox option for "Use course title?"  That would probably be better for the end user, especially non-technical ones, and it's a much simpler solution in the code.  Have there been use cases where the title needed to be more flexible than just using the course title or a custom title?  For example, showing the course title + the topic title (ex. "Adapt p101 - Topic 2")?

>  I was able to import the plugin fine without any errors but when I added the extension to a course the settings didn't display for me in the sidebar as expected (tested in AT v1.0.0-rc.2).

@chris-steele I'm running into a wall with getting the extension settings to show up for a course in the AAT (testing.kineoadapt.com).  Would you want to take a look?  Pretty sure `properties.schema` is set up properly because it added the expected JSON to `course.json` when I rebuilt a course.  I created `course.schema.json` via adapt-octopus.

**Comment by chris-steele** [comment]
@swashbuck I can't see an issue with it. @taylortom do you see any issue? Is any particular line ending/encoding required?

**Comment by kirsty-hames** [comment]
> What if we just made a new Boolean checkbox option for "Use course title?"

I think this is a great idea @swashbuck. Much better UX for the AAT.

**Review by kirsty-hames — COMMENTED** [review]
`_useCourseTitle` works for me thanks @swashbuck. 

To confirm, all issues approved once we're able to test and confirm #7 resolved.

File: templates/navigationTitle.jsx [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+export default function NavigationTitle(props) {
+  const {
+    title
+  } = props;
+
+  return (
+
+    <div className='navigation-title__inner'>
+      {title}
```
Comment (guywillis) [inline templates/navigationTitle.jsx]: Should we allow for escaped html characters here? Thinking there may be a potential need to pronounce characters individually through a screen reader.

Comment (chris-steele) [reply templates/navigationTitle.jsx]: Yes might be best to use `dangerouslySetInnerHTML` (https://reactjs.org/docs/dom-elements.html)

**Comment by guywillis** [comment]
Separate note to remove the `.u-float-none` css and change the framework requirement to `v5.24.4`

File: README.md [hunk 3]
```diff
@@ -1,3 +1,32 @@
...
+
+<img src='https://user-images.githubusercontent.com/898168/210417005-3c2f0e9d-b1f0-4a7b-815c-33c3a6921965.jpg' width="500" alt="Screenshot">
+
+### Attributes
+
+The following attributes are set within *course.json*.
+
+**\_navigationTitle** (object): The course.json Navigation Title target attribute object.
+
+>**\_isEnabled** (boolean): Controls whether the Navigation Title course object is enabled or not.
```
Comment (guywillis) [inline README.md]: Could the format of the readme entries follow the newer format please?

https://github.com/cgkineo/adapt-footer/pull/8/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R15

File: README.md [hunk 4]
```diff
@@ -1,3 +1,32 @@
...
+>**\_useCourseTitle** (boolean): Optional, use the course title as the navigation title. Will override anything in the `title` property of the `_navigationTitle` object.
+
+>**title** (string): The title text to display.
+
+## Limitations
+
+No known limitations
+
+----------------------------
+**Version number:**  1.0.0
```
Comment (guywillis) [inline README.md]: Could we change the double spacing at the end of the version number and subsequent lines to a html <br> tag instead to avoid the line breaks being removed when white space is removed.

File: bower.json [hunk 5]
```diff
@@ -1,11 +1,12 @@
 {
   "name": "adapt-navigationTitle",
   "version": "1.0.0",
-  "framework": ">=5",
+  "framework": ">=5.20.0",
```
Comment (guywillis) [inline bower.json]: With the removal of `.u-float-left` from the less this should be bumped to 5.24.4

File: package.json [hunk 6]
```diff
@@ -0,0 +1,17 @@
+{
+  "name": "adapt-navigationTitle",
+  "version": "1.0.0",
+  "framework": ">=5.20.0",
```
Comment (guywillis) [inline package.json]: With the removal of `.u-float-left` from the less this should be bumped to 5.24.4

File: README.md (hunk 3 above)
Comment (swashbuck) [reply README.md]: Should we include "AAT support" in the information at the bottom (ex. Version number, Author / maintainer, etc)?

File: README.md (hunk 4 above)
Comment (swashbuck) [reply README.md]: Done.

File: bower.json (hunk 5 above)
Comment (swashbuck) [reply bower.json]: Done.

**Review by guywillis — APPROVED** [review]
👍

**Review by chris-steele — APPROVED** [review]

**Comment by swashbuck** [comment]
Schemas updated and ready for a full review.

**Comment by kirsty-hames** [comment]
Hey @swashbuck, now that `_useCourseTitle` is a config option, do you think it makes sense to apply `aria-hidden` to the nav title as per https://github.com/cgkineo/adapt-navigationTitle/issues/5 ?

**Comment by swashbuck** [comment]
> Hey @swashbuck, now that `_useCourseTitle` is a config option, do you think it makes sense to apply `aria-hidden` to the nav title as per #5 ?

@kirsty-hames Yep, good spot.  I've hidden the title when it uses the same text as the course title.  I've also added aria-level="1" when _not_ using the course title.  This should address both concerns in #5 .

File: templates/navigationTitle.jsx [hunk 7]
```diff
@@ -2,12 +2,17 @@ import React from 'react';
...
+    _useCourseTitle
   } = props;
 
   return (
 
-    <div className='navigation-title__inner' dangerouslySetInnerHTML={{ __html: title }} />
+    <div
+      className='navigation-title__inner'
+      dangerouslySetInnerHTML={{ __html: title }}
+      aria-level={!_useCourseTitle ? 1 : null}
```
Comment (kirsty-hames) [inline templates/navigationTitle.jsx:14]: I think we'll need to include `role="heading"` too.

Comment (swashbuck) [reply templates/navigationTitle.jsx:14]: Yep, this is done.
